[package]
name = "pallet-evm-precompile-curve25519"
version = "1.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>", "Drew Stone <drew@webb.tools>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/frontier/"
description = "Curve25519 elliptic curve precompiles for EVM pallet."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-core = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-io = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
frame-support = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
pallet-evm = { version = "4.0.0-clover", default-features = false, path = "../.." }
fp-evm = { version = "2.0.0-clover", default-features = false, path = "../../../../primitives/evm" }
evm = { git = "https://github.com/clover-network/evm.git", tag = "v0.27.1-clover", default-features = false, features = ["with-codec"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

[dependencies.curve25519-dalek]
version = "3.0.0"
default-features = false
features = ["u64_backend", "alloc"]

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-io/std",
	"frame-support/std",
	"fp-evm/std",
	"evm/std",
	"codec/std",
]
