[package]
name = "substrate-test-runtime"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-application-crypto = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-consensus-aura = { version = "0.9.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-consensus-babe = { version = "0.9.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-block-builder = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0"}
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-executive = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-inherents = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-keyring = { version = "3.0.0", optional = true, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
memory-db = { version = "0.26.0", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0", default-features = false, version = "3.0.0"}
sp-core = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-std = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0", default-features = false, version = "3.0.0"}
sp-io = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
frame-support = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-version = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-session = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-api = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-runtime = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
pallet-babe = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
frame-system = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
frame-system-rpc-runtime-api = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
pallet-timestamp = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-finality-grandpa = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-trie = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-transaction-pool = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
trie-db = { version = "0.22.2", default-features = false }
parity-util-mem = { version = "0.9.0", default-features = false, features = ["primitive-types"] }
sc-service = { version = "0.9.0", default-features = false, optional = true, features = ["test-helpers"], path = "../../client/sc-service" }
sp-state-machine = { version = "0.9.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sp-externalities = { version = "0.9.0", default-features = false, git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }

# 3rd party
cfg-if = "1.0"
log = { version = "0.4.8", optional = true }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

[dev-dependencies]
sc-block-builder = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
sc-executor = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git", tag = "v3.0.0" }
substrate-test-runtime-client = { version = "2.0.0", path = "./client" }

[build-dependencies]
substrate-wasm-builder = "4.0.0"

[features]
default = [
	"std",
]
std = [
	"sp-application-crypto/std",
	"sp-consensus-aura/std",
	"sp-consensus-babe/std",
	"sp-block-builder/std",
	"codec/std",
	"frame-executive/std",
	"sp-inherents/std",
	"sp-keyring",
	"log",
	"memory-db/std",
	"sp-offchain/std",
	"sp-core/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime-interface/std",
	"sp-io/std",
	"frame-support/std",
	"sp-version/std",
	"serde",
	"sp-session/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-externalities/std",
	"sp-state-machine/std",
	"pallet-babe/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"sc-service",
	"sp-finality-grandpa/std",
	"sp-trie/std",
	"sp-transaction-pool/std",
	"trie-db/std",
]
